### ISSUE TITLE
Regression edition

### ISSUE THREAD

**Issue by Mmoi-Fr** [A7plusplus/A7plusplus#7]
L'option "n'afficher que les traductions les plus récentes" n'est plus respectée en 2.3.7.

**Comment by Mmoi-Fr** [comment]
@Aymkdn, il y a moyen que tu regardes ce pb ?

**Comment by Aymkdn** [comment]
Je pars ce matin en vacances jusqu'à mercredi... Pas sûr d'avoir le temps de regarder avant de prendre la route 😣

**Comment by Aymkdn** [comment]
Je viens de tester rapidement, et _"n'afficher que les traductions les plus récentes"_ semble fonctionner correctement chez moi ?! J'ai comparé avec la v2.3.6, et le même nombre de pages apparait, ça commence au même numéro de séquence, si je change de page ça va au bon numéro de séquence… Tu peux être plus précis sur ce qui ne marche pas ? Tu parles bien du bouton en haut à droite sur lequel on peut cliquer pour afficher ce qui n'est pas traduit encore ?

J'ai essayé avec la traduction de The Flash : https://www.addic7ed.com/translate.php?id=173934&fversion=0&langto=8&langfrom=1

Du coup, j'attends un rapport plus précis sur ce qui ne fonctionne pas, et je regarde ça à mon retour, mercredi aprem !

**Comment by Mmoi-Fr** [comment]
Attention, tu as envoyé la page de trad, pas celle d'édition :)
Sur la page d'édition, il y a une checkbox au dessus du filtre, et c'est elle qui pose problème.

Rien ne presse, passe de bonnes vacs :)

**Comment by Aymkdn** [comment]
Je regarde ça à mon retour ! 🙏

**Comment by Aymkdn** [comment]
Je suis rentré.

Alors, je ne vois pas ce qui ne fonctionne pas.

Exemple avec https://www.addic7ed.com/list.php?id=173934&fversion=0&lang=8&sequence=601

Donc sur la page 21, si la checkbox n'est pas cochée j'ai ça :
![image](https://user-images.githubusercontent.com/946315/160852238-b0be9713-7195-4d4c-af37-a64258e5dabd.png)

Et si je coche cette case : 
![image](https://user-images.githubusercontent.com/946315/160852352-e3deeb19-d6e4-4b97-b736-effbc2713d10.png)

J'obtiens : 
![image](https://user-images.githubusercontent.com/946315/160852430-3b1d6b7d-ec6f-4ed8-811b-7832a3dbf84f.png)

Ce qui me semble être le comportement attendu, non ?
Peux-tu me décrire précisément ce qui ne fonctionne pas stp ?

**Comment by Aymkdn** [comment]
Ah je crois que j'ai vu : la case ne reste pas cochée quand on change de page. Je vais regarder !

**Comment by Aymkdn** [comment]
Alors le plus simple est de bloquer le code qui pose problème lorsqu'on n'est pas sur la page de traduction : 
```js
    // on cherche à composer un lien unique qu'on pourra réutiliser plus tard sans devoir se rappeler à quelle page on est
    // ne s'applique qu'à la page de traduction
    if (window.location.pathname === "/translate.php") {
      let urlObject=new URL(window.location.href);
      // si on n'a pas les paramètres dans l'URL, alors on va recharger la page avec les bons paramètres
      if (!urlObject.searchParams.has("id")) {
        // cherche les paramètres relatives à la page
        if (page.queryInfos && page.queryInfos.id) window.location.href = `?id=${page.queryInfos.id}&fversion=${page.queryInfos.fversion}&langto=${page.queryInfos.lang}&langfrom=${page.queryInfos.langfrom}`;
        else console.log("[A7++ Error] `page.queryInfos.id` is not available. The URL cannot be built.");
      }
      // on modifie le lien de changement de page afin d'y ajouter le numéro de sequence
      // exemple du code appelé sur ces liens :
      //  - pour translate.php: href="javascript:list('210');linesChanged();""
      //  - pour list.php: href="noscript.php" onclick="apply_filter('', 'true', '630');return false;"
      // on change donc par une url avec tous les paramètres voulus
      let linkPages = document.querySelectorAll("#lista > a");
      let pageSourceUrl = window.location.href.replace(/&sequence=\d+/, "");
      for (let i=0; i<linkPages.length; i++) {
        let sequence = (linkPages[i].innerText-1)*30 + 1;
        linkPages[i].setAttribute("href", pageSourceUrl + "&sequence=" + sequence);
        linkPages[i].onclick = function(event) {
          event.preventDefault();
          if (window.history.pushState) {
            let newUrl = pageSourceUrl + "&sequence=" + sequence;
            window.history.pushState({}, '', newUrl);
          }
          
          list(''+(sequence-1));
          linesChanged();
        };
      }
    }
```

Si ça te semble OK, je ferai un _pull request_

**Comment by Mmoi-Fr** [comment]
> Alors le plus simple est de bloquer le code qui pose problème lorsqu'on n'est pas sur la page de traduction :
> 
> ```js
>     // on cherche à composer un lien unique qu'on pourra réutiliser plus tard sans devoir se rappeler à quelle page on est
>     // ne s'applique qu'à la page de traduction
>     if (window.location.pathname === "/translate.php") {
>       let urlObject=new URL(window.location.href);
>       // si on n'a pas les paramètres dans l'URL, alors on va recharger la page avec les bons paramètres
>       if (!urlObject.searchParams.has("id")) {
>         // cherche les paramètres relatives à la page
>         if (page.queryInfos && page.queryInfos.id) window.location.href = `?id=${page.queryInfos.id}&fversion=${page.queryInfos.fversion}&langto=${page.queryInfos.lang}&langfrom=${page.queryInfos.langfrom}`;
>         else console.log("[A7++ Error] `page.queryInfos.id` is not available. The URL cannot be built.");
>       }
>       // on modifie le lien de changement de page afin d'y ajouter le numéro de sequence
>       // exemple du code appelé sur ces liens :
>       //  - pour translate.php: href="javascript:list('210');linesChanged();""
>       //  - pour list.php: href="noscript.php" onclick="apply_filter('', 'true', '630');return false;"
>       // on change donc par une url avec tous les paramètres voulus
>       let linkPages = document.querySelectorAll("#lista > a");
>       let pageSourceUrl = window.location.href.replace(/&sequence=\d+/, "");
>       for (let i=0; i<linkPages.length; i++) {
>         let sequence = (linkPages[i].innerText-1)*30 + 1;
>         linkPages[i].setAttribute("href", pageSourceUrl + "&sequence=" + sequence);
>         linkPages[i].onclick = function(event) {
>           event.preventDefault();
>           if (window.history.pushState) {
>             let newUrl = pageSourceUrl + "&sequence=" + sequence;
>             window.history.pushState({}, '', newUrl);
>           }
>           
>           list(''+(sequence-1));
>           linesChanged();
>         };
>       }
>     }
> ```
> 
> Si ça te semble OK, je ferai un _pull request_

Je vérifie ça demain et te dis ;)

**Comment by Mmoi-Fr** [comment]
Après test, le `if (!page.translatePage)` règle le problème, mais la feature disparaît...
Autre note, si je fais un retour (à la page précédente), l'URL change, mais pas les lignes (Firefox, peut-être une conf chez moi, pour ça).

**Comment by Aymkdn** [comment]
> mais la feature disparaît

Oui, l'idée est de ne laisser la feature d'URL "d'accès direct" que sur la page translate, et pas sur la page d'édition.

> Autre note, si je fais un retour (à la page précédente), l'URL change, mais pas les lignes (Firefox, peut-être une conf chez moi, pour ça).

En théorie ça devrait marcher, mais je ferai des tests demain.

**Comment by Aymkdn** [comment]
Alors je viens de modifier et j'ai pushé dans mon repo si tu veux tester : https://github.com/Aymkdn/A7plusplus-2

J'ai utilisé `if (page.translatePage)`, et le changement d'URL via l'historique du navigateur (comme "page précédente") charge maintenant les bonnes séquences.

**Comment by Mmoi-Fr** [comment]
> > mais la feature disparaît
> 
> Oui, l'idée est de ne laisser la feature d'URL "d'accès direct" que sur la page translate, et pas sur la page d'édition.

Pourquoi ne faire la feature que dans un seul des deux modes ?

`window.addEventListener('popstate', function() {` Je l'aurais vu dans A7Init.js, puisqu'on a juste besoin de le déclarer qu'une fois.

Sinon, l'historique fonctionne bien désormais

**Comment by Aymkdn** [comment]
> Pourquoi ne faire la feature que dans un seul des deux modes ?

Je ne suis pas sûr que ce soit bien utile pour la page d'édition ? Et j'ai essayé de l'adapter, mais ça demande des bidouillages plus poussés… Je n'ai jamais utilisé la page d'édition donc faudrait que j'y passe plus de temps dessus aussi. Pour le moment, je préfère réserver ça pour une prochaine version.

> Je l'aurais vu dans A7Init.js, puisqu'on a juste besoin de le déclarer qu'une fois.

Bonne idée : je l'ai déplacé dans `preInit()` qui semble n'être appelé qu'une fois. J'ai mis à jour le repo.

**Comment by Mmoi-Fr** [comment]
PArfait, tu peux faire une pull request avec le texte "Fix: #7", ca devrait automatiquement fix l'issue ;)
